### ISSUE TITLE
No package metadata was found for djhtml ? 

### ISSUE THREAD

**Issue by anrudolph** [rtts/djhtml#123]
I installed djhtml via
```
pip install djhtml
```
in a venv. Then I ran the code via
```bash 
djhtml .
```
and got the following error message:

Traceback (most recent call last):
  File "/usr/lib/python3.12/importlib/metadata/__init__.py", line 397, in from_name
    return next(cls.discover(name=name))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
StopIteration

During handling of the above exception, another exception occurred:

```bash 
Traceback (most recent call last):
  File "/usr/bin/djhtml", line 33, in <module>
    sys.exit(load_entry_point('djhtml==3.0.6', 'console_scripts', 'djhtml')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/djhtml", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/metadata/__init__.py", line 862, in distribution
    return Distribution.from_name(distribution_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/metadata/__init__.py", line 399, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for djhtml
```

A Google search found problems with importlib for many other python packages, too. Maybe this is a problem between djhtml and python 3.12?

Do you have any suggestions on this?

**Comment by JaapJoris** [comment]
I could not reproduce this using Python 3.12.4.

Can anyone else reproduce this?
